#!/bin/python3 

"""CONSERTA ISSO PLMD"""

import sys
import re

from CCrawler import Chicken

try:
    START = sys.argv[1]

except IndexError:
    print("USAGE: efinder [ADRESS]")
    sys.exit()

TO_CRAWL = [START]
CRAWLED = set()

while True:
    if TO_CRAWL == []:
            break
    
    webpage = Chicken.get_page(TO_CRAWL[0])
    links = Chicken.find_links(webpage.text)
    emails = re.findall(r"\w[\w\.]+\w@\w[\w\.]+\w", webpage)

    for e in emails:
        print(f"[E!] FOUND {e} IN {TO_CRAWL[0]}")
    
    oldlink = TO_CRAWL[0]
    TO_CRAWL.pop(0)
    
    for l in links:
        if l not in TO_CRAWL and l not in CRAWLED:
            print(f"[!] FOUND {l}")
            if l[0:4] == "http":
                TO_CRAWL.append(l)
                # CRAWLED.add(l)

    CRAWLED.add(oldlink)
