#!/bin/python3

import sys

import paramiko

try:
    HOST = sys.argv[1]
    USER = sys.argv[2] 
    PASSWD = sys.argv[3]

except:
    print("USAGE: ssh_client [HOST] [USER] [PASSWORD]")

CLIENT = paramiko.SSHClient()
CLIENT.set_missing_host_key_policy(paramiko.AutoAddPolicy()) # DISABLE KNOW_HOSTS
CLIENT.connect(HOST, username=USER, password=PASSWD)

while True:
    stdin, stdout, stderr = CLIENT.exec_command(str(input("($) >>> ").strip()))
    for line in stdout.readlines():
        print(line.strip())

    errors = stderr.readlines()
    if errors:
        print(errors)
