#!/bin/python3

import json

import requests

FILE = open('emails.txt', 'a')

EMAILS = set()

for p in range(36):
    response = requests.get(f"http://shop.bancocn.com/rest/products/{p}/reviews")
    content = json.loads(response.text)
    if content["data"] != [] and content["data"][0]["author"] not in EMAILS:
        email = content["data"][0]["author"]
        EMAILS.add(email)
        FILE.write(email + '\n')
