#!/bin/python3
import sys
import requests

try:
    ADRESS = sys.argv[1]
    WORDLIST = sys.argv[2]

except IndexError:
    print("USAGE: dirbrute [ADRESS] [WORDLIST]")
    sys.exit()

W_PATH = open(WORDLIST, 'r')
DIRS = W_PATH.readlines()


for word in DIRS:
    sub_adress = f"{ADRESS}/{word.strip()}"
    response = requests.get(sub_adress)
    if response.status_code == 200:
        print(f"[!] FOUND {sub_adress} (CODE: {response.status_code})")
    else:
        print(f"[*] NOT FOUND {sub_adress} (CODE: {response.status_code})")



